source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from .views import ServiceListView, DentistListView, contact_us, Services, PricingListView, appointment, BlogListView, \
    BlogCategoryListView, BlogSearchView, BlogDetailView

urlpatterns = [
    path('', ServiceListView.as_view(), name='home'),
    path('dent/about/us/', DentistListView.as_view(), name='about_us'),
    path('dent/contact/us/', contact_us, name='contact_us'),
    path('dent/services/', Services.as_view(), name='services'),
    path('dent/pricing/', PricingListView.as_view(), name='price'),
    path('dent/appointment/', appointment, name='appointment'),
    path('dent/blogs/', BlogListView.as_view(), name='blogs'),
    path('dent/blogs/category/<int:pk>/', BlogCategoryListView.as_view(), name='category'),
    path('dent/blogs/search/', BlogSearchView.as_view(), name='search'),
    path('dent/blog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail')
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models


class Service(models.Model):
    name = models.CharField(max_length=2000, verbose_name='Service')
    stage = models.CharField(max_length=50, verbose_name='Stage')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'
        ordering = ['name']


class Dentist(models.Model):
    image = models.ImageField(upload_to='dentist_images', verbose_name='Dentist image')
    name = models.CharField(max_length=40, verbose_name='Name')
    last_name = models.CharField(max_length=40, verbose_name='Last name')
    position = models.CharField(max_length=40, verbose_name='Position')
    facebook = models.CharField(max_length=60, verbose_name='Facebook link')
    twitter = models.CharField(max_length=60, verbose_name='Twitter link')
    google = models.CharField(max_length=60, verbose_name='Google Link')

    def __str__(self):
        return "{} - {}".format(self.name, self.position)

    class Meta:
        verbose_name = 'Dentist'
        verbose_name_plural = 'Dentists'


class AboutUs(models.Model):
    description = models.TextField(max_length=2000, verbose_name='Description')

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'About Us'
        verbose_name_plural = 'About Us'


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    description = models.TextField(max_length=3000, verbose_name='First Paragraph')
    second_description = models.TextField(max_length=3000, verbose_name='Second Paragraph')
    quote = models.CharField(max_length=200, null=True, blank=True, verbose_name='Quote')
    quote_author = models.CharField(max_length=60, null=True, blank=True, verbose_name='Quote author')
    quote_author_position = models.CharField(max_length=70, null=True, blank=True, verbose_name='Quote Author Position')
    third_description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Third Paragraph')
    fourth_description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Fourth Paragraph')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created on')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated at')
    category = models.ForeignKey('webapp.Category', on_delete=models.PROTECT, null=False, blank=False,
                                 verbose_name='Blog Category',
                                 related_name='blog_category')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'
        ordering = ('-created_at',)


class BlogPhoto(models.Model):
    photo = models.ImageField(upload_to='blog_images', verbose_name='Photo')
    blog_id = models.ForeignKey('webapp.Blog', null=False, blank=False, on_delete=models.CASCADE,
                                 verbose_name='Blog', related_name='photo_blogs')

    class Meta:
        verbose_name = 'Blog Photo'
        verbose_name_plural = 'Blog Photos'


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='Category')

    def __str__(self):
        return  self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class UserFeedBack(models.Model):
    image = models.ImageField(upload_to='user_images', verbose_name='Photo', null=True, blank=True)
    name= models.CharField(max_length=60, verbose_name='User Name')
    l_name = models.CharField(max_length=60, verbose_name='Last Name')
    feedback = models.TextField(max_length=2000, verbose_name='Feedback')
    position = models.CharField(max_length=80, null=True, blank=True, verbose_name='Position')

    def __str__(self):
        return "{} - {}".format(self.name, self.feedback)

    class Meta:
        verbose_name = 'User Feedback'
        verbose_name_plural = 'User Feedbacks'

source/webapp/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.core.mail import send_mail

from webapp.models import Service, Dentist, AboutUs, Category, Blog, UserFeedBack


class ServiceListView(ListView):
    model = Service
    template_name = 'dent/index.html'
    context_object_name = 'services'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dentists'] = Dentist.objects.all()
        context['info_description'] = AboutUs.objects.get(id=1)
        context['user_feedbacks'] = UserFeedBack.objects.all()
        blogs = Blog.objects.all().order_by('-created_at')
        paginator = Paginator(blogs, 3)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['blogs'] = page_obj
        return context


class DentistListView(ListView):
    model = Dentist
    template_name = 'dent/about.html'
    context_object_name = 'dentists'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['aboutus'] = AboutUs.objects.get(id=1)
        context['user_feedbacks'] = UserFeedBack.objects.all()
        return context


def contact_us(request):
    if request.method == 'POST':
        message_name = request.POST.get('message-name')
        message_email = request.POST.get('message-email')
        message = request.POST.get('message')
        # send an email
        send_mail(
            message_name, # subject
            message + " " + message_email, # message and message_email in order to know who filled out form and sent. User email can't send message directory to gmail service.
            '', # From email. Here needs to be an email that you use for smtp server.
            ['',], # To email, you can send to multiple users on form.

        )
        return render(request, 'dent/contact.html', {'message_name': message_name})
    return render(request, 'dent/contact.html', {})


class Services(ListView):
    model = Blog
    template_name = 'dent/service.html'
    context_object_name = 'blogs'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['user_feedbacks'] = UserFeedBack.objects.all()
        return  context


class PricingListView(ListView):
    model = Service
    template_name = 'dent/pricing.html'
    context_object_name = 'prices'


def appointment(request):
    if request.method == 'POST':
        your_name = request.POST.get('your-name')
        your_phone = request.POST.get('your-phone')
        your_email = request.POST.get('your-email')
        your_address = request.POST.get('your-address')
        your_schedule = request.POST.get('your-schedule')
        your_date = request.POST.get('your-date')
        your_message = request.POST.get('your-message')

        # send an email

        appointment = "Name: " + your_name + "\n" + "Phone: " + your_phone + "\n" + "Email: "\
                      + your_email + "\n" + "Address: " + your_address + "\n" + "Schedule: " + your_schedule + "\n" + "Date: " \
                      + your_date + "\n" + "Message: " + your_message
        send_mail(
            'Appointment Request', #subject
            appointment, # message
            '', # from email
            [''] # To email

        )
        return render(request, 'dent/appointment.html', {
            'your_name': your_name,
            'your_phone': your_phone,
            'your_email': your_email,
            'your_address': your_address,
            'your_schedule': your_schedule,
            'your_date': your_date,
            'your_message': your_message,
        })
    return render(request, 'dent/index.html', {})


class BlogListView(ListView):
    model = Blog
    template_name = 'dent/blog.html'
    context_object_name = 'blogs'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BlogCategoryListView(ListView):
    model = Blog
    template_name = 'dent/category.html'
    context_object_name = 'category'

    def get_queryset(self):
        return Blog.objects.filter(category_id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BlogSearchView(ListView):
    model = Blog
    template_name = 'dent/search.html'

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query == "":
            messages.add_message(self.request, messages.WARNING, 'Please fill out the search bar.')
        object_list = Blog.objects.filter(
            Q(title__icontains=query) | Q(description__contains=query)
        )
        return object_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'dent/blog-details.html'
    context_object_name = 'blog'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

source/webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="{% block meta_description %}Welcome to the dentist website.{% endblock %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Title -->
  <title>{% block title %} Dento - Dentist &amp; Medical HTML Template {% endblock %}</title>

  <!-- Favicon -->
  <link rel="icon" href="{% static 'webapp/img/core-img/favicon.ico' %}">

  <!-- Core Stylesheet -->
  <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">

</head>

<body>
  <!-- Preloader -->
  <div id="preloader">
    <div class="preload-content">
      <div id="dento-load"></div>
    </div>
  </div>

  <!-- ***** Header Area Start ***** -->
  <header class="header-area">
    <!-- Top Header Area -->
    <div class="top-header-area">
      <div class="container h-100">
        <div class="row h-100 align-items-center">
          <!-- Top Content -->
          <div class="col-6 col-md-9 col-lg-8">
            <div class="top-header-content">
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="28 Jackson Street, Chicago, 7788569 USA"><i class="fa fa-map-marker"></i> <span>28 Jackson Street, Chicago, 7788569 USA</span></a>
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="info.dento@gmail.com"><i class="fa fa-envelope"></i> <span>info.dento@gmail.com</span></a>
            </div>
          </div>
          <!-- Top Header Social Info -->
          <div class="col-6 col-md-3 col-lg-4">
            <div class="top-header-social-info text-right">
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="Linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Top Header End -->

    <!-- Main Header Start -->
    <div class="main-header-area">
      <div class="classy-nav-container breakpoint-off">
        <div class="container">
          <!-- Classy Menu -->
          <nav class="classy-navbar justify-content-between" id="dentoNav">

            <!-- Logo -->
            <a class="nav-brand" href="{% url 'webapp:home' %}"><img src="{% static 'webapp/img/core-img/logo.png' %}" alt=""></a>

            <!-- Navbar Toggler -->
            <div class="classy-navbar-toggler">
              <span class="navbarToggler"><span></span><span></span><span></span></span>
            </div>

            <!-- Menu -->
            <div class="classy-menu">

              <!-- Close Button -->
              <div class="classycloseIcon">
                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
              </div>

              <!-- Nav Start -->
              <div class="classynav">
                <ul id="nav">
                  <li><a href="{% url 'webapp:home' %}">Home</a></li>
                  <li><a href="{% url 'webapp:about_us' %}">About</a></li>
                  <li><a href="{% url 'webapp:services' %}">Service</a></li>
                  <li><a href="{% url 'webapp:price' %}">Pricing</a></li>
                  <li><a href="{% url 'webapp:blogs' %}">Blog</a></li>
                  <li><a href="{% url 'webapp:contact_us' %}">Contact</a></li>
                </ul>
              </div>
              <!-- Nav End -->
            </div>

            <!-- Booking Now Button -->
            <a href="#opening" class="btn dento-btn booking-btn">Booking Now</a>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  {% block  content %} {% endblock %}


  <!-- ***** Footer Area Start ***** -->
  <footer class="footer-area bg-img bg-gradient-overlay" style="background-image: url({% static 'webapp/img/bg-img/3.jpg' %});">
    <div class="container">
      <div class="row">
        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-footer-widget">
            <a href="{% url 'webapp:home' %}" class="d-block mb-4"><img src="{% static 'webapp/img/core-img/logo.png' %}" alt=""></a>
            <p>Etiam sutor risus, dapibus act elefend katen, lacinia sitamet denim. Mauris sagittis kansa interdum dignissim.</p>
            <div class="footer-contact">
              <p><i class="icon_pin"></i> 28 Jackson Street, Chicago, 7788569 USA</p>
              <p><i class="icon_phone"></i> +84. 2252. 2250. 122</p>
              <p><i class="icon_mail"></i> info.dento@gmail.com</p>
            </div>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Opening Hours</h5>

            <!-- Opening Hours -->
            <ul class="opening-hours">
              <li><span>Mon-Wed</span> <span>8.00-18.00</span></li>
              <li><span>Thu-Fri</span> <span>8.00-17.00</span></li>
              <li><span>Sat</span> <span>9.00-17.00</span></li>
              <li><span>Sun</span> <span>10.00-17.00</span></li>
              <li><span>Holiday</span> <span>Closed</span></li>
            </ul>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Quick Link</h5>

            <!-- Quick Links Nav -->
            <nav>
              <ul class="quick-links">
                <li><a href="{% url 'webapp:about_us' %}">About Us</a></li>
                <li><a hidden href="#">FAQs</a></li>
                <li><a href="{% url 'webapp:contact_us' %}">Contact</a></li>
                <li><a hidden href="#">Policy</a></li>
                <li><a href="{% url 'webapp:blogs' %}">Blog</a></li>
                <li><a hidden href="#">Advisors</a></li>
                <li><a href="{% url 'webapp:price' %}">Pricing</a></li>
                <li><a hidden href="#">Dentist</a></li>
                <li><a href="{% url 'webapp:services' %}">Services</a></li>
                <li><a hidden href="#">Legals</a></li>
              </ul>
            </nav>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Find us</h5>

            <p>Follow us on social media.</p>

            <!-- Social Info -->
            <div class="footer-social-info">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Copywrite Area -->
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="copywrite-content">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- ***** Footer Area End ***** -->

  <!-- ******* All JS ******* -->
  <!-- jQuery js -->
  <script src="{% static 'webapp/js/jquery.min.js' %}"></script>
  <!-- Popper js -->
  <script src="{% static 'webapp/js/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'webapp/js/bootstrap.min.js' %}"></script>
  <!-- All js -->
  <script src="{% static 'webapp/js/dento.bundle.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'webapp/js/default-assets/active.js' %}"></script>

</body>

</html>