source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from .views import ServiceListView, DentistListView, contact_us, Services, PricingListView, appointment, BlogListView, \
    BlogCategoryListView, BlogSearchView, BlogDetailView

urlpatterns = [
    path('', ServiceListView.as_view(), name='home'),
    path('dent/about/us/', DentistListView.as_view(), name='about_us'),
    path('dent/contact/us/', contact_us, name='contact_us'),
    path('dent/services/', Services.as_view(), name='services'),
    path('dent/pricing/', PricingListView.as_view(), name='price'),
    path('dent/appointment/', appointment, name='appointment'),
    path('dent/blogs/', BlogListView.as_view(), name='blogs'),
    path('dent/blogs/category/<int:pk>/', BlogCategoryListView.as_view(), name='category'),
    path('dent/blogs/search/', BlogSearchView.as_view(), name='search'),
    path('dent/blog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail')
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models


class Service(models.Model):
    name = models.CharField(max_length=2000, verbose_name='Service')
    stage = models.CharField(max_length=50, verbose_name='Stage')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'
        ordering = ['name']


class Dentist(models.Model):
    image = models.ImageField(upload_to='dentist_images', verbose_name='Dentist image')
    name = models.CharField(max_length=40, verbose_name='Name')
    last_name = models.CharField(max_length=40, verbose_name='Last name')
    position = models.CharField(max_length=40, verbose_name='Position')
    facebook = models.CharField(max_length=60, verbose_name='Facebook link')
    twitter = models.CharField(max_length=60, verbose_name='Twitter link')
    google = models.CharField(max_length=60, verbose_name='Google Link')

    def __str__(self):
        return "{} - {}".format(self.name, self.position)

    class Meta:
        verbose_name = 'Dentist'
        verbose_name_plural = 'Dentists'


class AboutUs(models.Model):
    description = models.TextField(max_length=2000, verbose_name='Description')

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'About Us'
        verbose_name_plural = 'About Us'


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    description = models.TextField(max_length=3000, verbose_name='First Paragraph')
    second_description = models.TextField(max_length=3000, verbose_name='Second Paragraph')
    quote = models.CharField(max_length=200, null=True, blank=True, verbose_name='Quote')
    quote_author = models.CharField(max_length=60, null=True, blank=True, verbose_name='Quote author')
    quote_author_position = models.CharField(max_length=70, null=True, blank=True, verbose_name='Quote Author Position')
    third_description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Third Paragraph')
    fourth_description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Fourth Paragraph')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created on')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated at')
    category = models.ForeignKey('webapp.Category', on_delete=models.PROTECT, null=False, blank=False,
                                 verbose_name='Blog Category',
                                 related_name='blog_category')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'
        ordering = ('-created_at',)


class BlogPhoto(models.Model):
    photo = models.ImageField(upload_to='blog_images', verbose_name='Photo')
    blog_id = models.ForeignKey('webapp.Blog', null=False, blank=False, on_delete=models.CASCADE,
                                 verbose_name='Blog', related_name='photo_blogs')

    class Meta:
        verbose_name = 'Blog Photo'
        verbose_name_plural = 'Blog Photos'


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='Category')

    def __str__(self):
        return  self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class UserFeedBack(models.Model):
    image = models.ImageField(upload_to='user_images', verbose_name='Photo', null=True, blank=True)
    name= models.CharField(max_length=60, verbose_name='User Name')
    l_name = models.CharField(max_length=60, verbose_name='Last Name')
    feedback = models.TextField(max_length=2000, verbose_name='Feedback')
    position = models.CharField(max_length=80, null=True, blank=True, verbose_name='Position')

    def __str__(self):
        return "{} - {}".format(self.name, self.feedback)

    class Meta:
        verbose_name = 'User Feedback'
        verbose_name_plural = 'User Feedbacks'

source/webapp/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.core.mail import send_mail

from webapp.models import Service, Dentist, AboutUs, Category, Blog, UserFeedBack


class ServiceListView(ListView):
    model = Service
    template_name = 'dent/index.html'
    context_object_name = 'services'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dentists'] = Dentist.objects.all()
        context['info_description'] = AboutUs.objects.get(id=1)
        context['user_feedbacks'] = UserFeedBack.objects.all()
        blogs = Blog.objects.all().order_by('-created_at')
        paginator = Paginator(blogs, 3)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['blogs'] = page_obj
        return context


class DentistListView(ListView):
    model = Dentist
    template_name = 'dent/about.html'
    context_object_name = 'dentists'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['aboutus'] = AboutUs.objects.get(id=1)
        context['user_feedbacks'] = UserFeedBack.objects.all()
        return context


def contact_us(request):
    if request.method == 'POST':
        message_name = request.POST.get('message-name')
        message_email = request.POST.get('message-email')
        message = request.POST.get('message')
        # send an email
        send_mail(
            message_name, # subject
            message + " " + message_email, # message and message_email in order to know who filled out form and sent. User email can't send message directory to gmail service.
            '', # From email. Here needs to be an email that you use for smtp server.
            ['',], # To email, you can send to multiple users on form.

        )
        return render(request, 'dent/contact.html', {'message_name': message_name})
    return render(request, 'dent/contact.html', {})


class Services(ListView):
    model = Blog
    template_name = 'dent/service.html'
    context_object_name = 'blogs'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['user_feedbacks'] = UserFeedBack.objects.all()
        return  context


class PricingListView(ListView):
    model = Service
    template_name = 'dent/pricing.html'
    context_object_name = 'prices'


def appointment(request):
    if request.method == 'POST':
        your_name = request.POST.get('your-name')
        your_phone = request.POST.get('your-phone')
        your_email = request.POST.get('your-email')
        your_address = request.POST.get('your-address')
        your_schedule = request.POST.get('your-schedule')
        your_date = request.POST.get('your-date')
        your_message = request.POST.get('your-message')

        # send an email

        appointment = "Name: " + your_name + "\n" + "Phone: " + your_phone + "\n" + "Email: "\
                      + your_email + "\n" + "Address: " + your_address + "\n" + "Schedule: " + your_schedule + "\n" + "Date: " \
                      + your_date + "\n" + "Message: " + your_message
        send_mail(
            'Appointment Request', #subject
            appointment, # message
            '', # from email
            [''] # To email

        )
        return render(request, 'dent/appointment.html', {
            'your_name': your_name,
            'your_phone': your_phone,
            'your_email': your_email,
            'your_address': your_address,
            'your_schedule': your_schedule,
            'your_date': your_date,
            'your_message': your_message,
        })
    return render(request, 'dent/index.html', {})


class BlogListView(ListView):
    model = Blog
    template_name = 'dent/blog.html'
    context_object_name = 'blogs'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BlogCategoryListView(ListView):
    model = Blog
    template_name = 'dent/category.html'
    context_object_name = 'category'

    def get_queryset(self):
        return Blog.objects.filter(category_id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BlogSearchView(ListView):
    model = Blog
    template_name = 'dent/search.html'

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query == "":
            messages.add_message(self.request, messages.WARNING, 'Please fill out the search bar.')
        object_list = Blog.objects.filter(
            Q(title__icontains=query) | Q(description__contains=query)
        )
        return object_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'dent/blog-details.html'
    context_object_name = 'blog'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

source/webapp/templates/dent/about.html
{% extends 'base.html' %}
{% block title %} Dento - Dentist &amp; Medical HTML Template {% endblock %}
{% block meta_description %}This is the about page of the Dentist!{% endblock %}
{% load static %}
{% block content %}

  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'webapp/img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">About Us</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'webapp:home' %}"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">About Us</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ****** About Us Area Start ******* -->
  <section class="dento-about-us-area mt-70">
    <div class="container">
      <div class="row align-items-center">
        <!-- About Us Thumbnail -->
        <div class="col-12 col-md-6">
          <div class="about-us-thumbnail mb-50">
            <img src="{% static 'webapp/img/bg-img/15.jpg' %}" alt="">
          </div>
        </div>
        <!-- About Content -->
        <div class="col-12 col-md-6">
          <div class="about-us-content mb-50">
            <!-- Section Heading -->
            <div class="section-heading">
              <h2>About Us</h2>
              <div class="line"></div>
            </div>
            <p>
                {{ aboutus.description }}
            </p>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Experience Dentist</h6>
              <div id="bar1" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="80"></span>
              </div>
            </div>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Modern Equipment</h6>
              <div id="bar2" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="65"></span>
              </div>
            </div>

            <!-- Single Skills Area -->
            <div class="single-skills-area mt-30">
              <h6>Friendly Staff</h6>
              <div id="bar3" class="barfiller">
                <span class="tip"></span>
                <span class="fill" data-percentage="85"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ****** About Us Area End ****** -->

  <div class="container">
    <div class="dento-border clearfix"></div>
  </div>

  <!-- Cool Facts Area Start -->
  <section class="dento-cta-area">
    <div class="container">
      <div class="row">
        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_genius"></i>
            <h2><span class="counter">20</span></h2>
            <h5>Years Of Experience</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_heart_alt"></i>
            <h2><span class="counter">700</span>+</h2>
            <h5>Happy Patients</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_book_alt"></i>
            <h2><span class="counter">120</span></h2>
            <h5>Certificate</h5>
          </div>
        </div>

        <!-- Cool Facts Area -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-cta text-center mt-50 mb-100">
            <i class="icon_id"></i>
            <h2><span class="counter">40</span>+</h2>
            <h5>Dentist</h5>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Cool Facts Area End -->

  <!-- ***** Testimonials Area Start ***** -->
  <section class="testimonials-area section-padding-100 bg-img bg-gradient-overlay jarallax clearfix" style="background-image: url({% static 'webapp/img/bg-img/7.jpg' %});">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <!-- Testimonials Slides -->
          <div class="testimonials-slides owl-carousel">
            <!-- Single Testimonials Slide -->
              {% include 'partial/testimonials.html' %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ***** Testimonials Area End ***** -->

  <!-- ***** Dento Dentist Area Start ***** -->
  <section class="dentist-area section-padding-100-0">
    <div class="container">
      <div class="row">
        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>Our Dentist</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row">
        <!-- Single Dentist Area -->
          {% for dentist in dentists %}
        <div class="col-12 col-sm-6 col-md-4">
          <div class="single-dentist-area mb-100">
            <img src="{{ dentist.image.url }}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">
                <a href="{{ dentist.facebook }}"><i class="fa fa-facebook"></i></a>
                <a href="{{ dentist.twitter }}"><i class="fa fa-twitter"></i></a>
                <a href="{{ dentist.google }}"><i class="fa fa-google-plus"></i></a>
              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                <h5>{{ dentist.name }} {{ dentist.last_name }}</h5>
                <p>{{ dentist.position }}</p>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </section>
  <!-- ***** Dento Dentist Area End ***** -->

{% endblock %}

source/webapp/templates/dent/blog.html
{% extends 'base.html' %}
{% block title %}Dento - Dentist &amp; Medical HTML Template{% endblock %}
{% block meta_description %}This is blog page {% endblock %}
{% load static %}
{% block content %}
    <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'webapp/img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Blog</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'webapp:home' %}"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Blog</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- *****Blog Area Start ***** -->
  <section class="dento-blog-area mt-50">
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-8">

          <!-- Single Blog Item -->
            {% for blog in blogs %}
          <div class="single-blog-item style-2 d-flex flex-wrap align-items-center mb-50">
            <!-- Blog Thumbnail -->
            <div class="blog-thumbnail">
              <a href="{% url 'webapp:blog_detail' blog.pk %}">
              {% for photo_blog in blog.photo_blogs.all %}
                  {% if forloop.first %}
                      <img src="{{ photo_blog.photo.url }}" alt="">
                  {% endif %}
              {% endfor %}
              </a>
            </div>
            <!-- Blog Content -->
            <div class="blog-content">
              <a href="{% url 'webapp:blog_detail' blog.pk %}" class="post-title">{{ blog.title }}</a>
              <p>{{ blog.description|truncatewords:21 }}</p>
              <div class="post-meta">
                <a href="#"><i class="icon_clock_alt"></i> {{ blog.created_at| date:"M d" }}</a>
              </div>
            </div>
          </div>
            {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        </div>
        <!-- Dento Sidebar Area -->
        <div class="col-12 col-lg-4">
          <div class="dento-sidebar">
              {% include 'partial/categories_and_search_form.html' %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- *****Blog Area End ***** -->
{% endblock %}

source/webapp/templates/dent/category.html
{% extends 'base.html' %}
{% block title %}Dento - Dentist &amp; Medical HTML Template{% endblock %}
{% block meta_description %}Dent Category page {% endblock %}
{% load static %}
{% block content %}
    <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'webapp/img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Blog</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'webapp:home' %}"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Blog</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- *****Blog Area Start ***** -->
  <section class="dento-blog-area mt-50">
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-8">

          <!-- Single Blog Item -->
            {% for post in category %}
          <div class="single-blog-item style-2 d-flex flex-wrap align-items-center mb-50">
            <!-- Blog Thumbnail -->
            <div class="blog-thumbnail">
              <a href="./blog-details.html">
              {% for photo_blog in post.photo_blogs.all %}
                  {% if forloop.first %}
                      <img src="{{ photo_blog.photo.url }}" alt="">
                  {% endif %}
              {% endfor %}
              </a>
            </div>
            <!-- Blog Content -->
            <div class="blog-content">
              <a href="./blog-details.html" class="post-title">{{ post.title }}</a>
              <p>{{ post.description|truncatewords:21 }}</p>
              <div class="post-meta">
                <a href="#"><i class="icon_clock_alt"></i> {{ post.created_at|date:"M d" }}</a>
{#                <a href="#"><i class="icon_chat_alt"></i> 3 Comments</a>#}
              </div>
            </div>
          </div>
            {% empty %}
                <h1>No post</h1>
            {% endfor %}

          <!-- Pagination -->
          <nav class="dento-pagination mb-100">
            <ul class="pagination">
              <li class="page-item active"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
          </nav>
        </div>

        <!-- Dento Sidebar Area -->
        <div class="col-12 col-lg-4">
          <div class="dento-sidebar">

            <!-- Single Widget Area -->
            <div class="single-widget-area search-widget">
              <form action="{% url 'webapp:search' %}" method="get">
                <input type="search" name="query" class="form-control" placeholder="Search ...">
                <button type="submit"><i class="icon_search"></i></button>
              </form>
            </div>

            <!-- Single Widget Area -->
            <div class="single-widget-area catagories-widget">
              <h5 class="widget-title">Categories</h5>

              <!-- catagories list -->
              <ul class="catagories-list">
                  {% for category in categories %}
                      <li><a href="{% url 'webapp:category' category.pk %}">{{ category.name }}</a></li>
                  {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- *****Blog Area End ***** -->
{% endblock %}

source/webapp/templates/dent/service.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block meta_description %}Dental service page {% endblock %}
{% load static %}
{% block content %}

  <!-- ***** Breadcrumb Area Start ***** -->
  <div class="breadcumb-area bg-img bg-gradient-overlay" style="background-image: url({% static 'webapp/img/bg-img/12.jpg' %});">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">
          <h2 class="title">Service</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcumb--con">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'webapp:home' %}"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Service</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ***** Breadcrumb Area End ***** -->

  <!-- ***** Services Area Start ***** -->
  <section class="dento-services-area mt-50 mb-50">
    <div class="container">
      <div class="row">

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'webapp/img/core-img/s6.png' %}" alt="">
            </div>
            <h5>Teeth Whitening</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'webapp/img/core-img/s7.png' %}" alt="">
            </div>
            <h5>Dental Implants</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'webapp/img/core-img/s8.png' %}" alt="">
            </div>
            <h5>Missing Teeth</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'webapp/img/core-img/s9.png' %}" alt="">
            </div>
            <h5>Cosmetic Dentistry</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'webapp/img/core-img/s10.png' %}" alt="">
            </div>
            <h5>Examination</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

        <!-- Single Service Area -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-service--area text-center mb-50">
            <div class="icon--">
              <img src="{% static 'webapp/img/core-img/s6.png' %}" alt="">
            </div>
            <h5>Teeth Pain</h5>
            <p>In pretium neque a libero congue. Elit diam lectus. Prasent lacinia vitae sit
              mattis mollis maximus.</p>
          </div>
        </div>

      </div>
    </div>
  </section>
  <!-- ***** Services Area End ***** -->

  <!-- ***** Testimonials Area Start ***** -->
  <section class="testimonials-area section-padding-100 bg-img bg-gradient-overlay jarallax clearfix" style="background-image: url({% static 'webapp/img/bg-img/7.jpg' %});">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <!-- Testimonials Slides -->
          <div class="testimonials-slides owl-carousel">
              {% include 'partial/testimonials.html' %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ***** Testimonials Area End ***** -->

  <!-- ***** Blog Area Start ***** -->
  <section class="dento-blog-area section-padding-100-0 clearfix">
    <div class="container">
      <div class="row">
        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>The Latest News</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row">
        <!-- Single Blog Item -->
          {% for blog in blogs %}
        <div class="col-12 col-md-6 col-lg-4">
          <div class="single-blog-item mb-100">
            <a href="{% url 'webapp:blog_detail' blog.pk %}">
                {% for photo_blog in blog.photo_blogs.all %}
                    {% if forloop.first %}
                        <img src="{{ photo_blog.photo.url }}" alt="">
                    {% endif %}
                {% endfor %}
            </a>
            <!-- Blog Content -->
            <div class="blog-content">
              <a href="{% url 'webapp:blog_detail' blog.pk %}" class="post-title">{{ blog.title }}</a>
              <p>{{ blog.description|truncatewords:21 }}</p>
              <div class="post-meta">
                <a href="{% url 'webapp:blog_detail' blog.pk %}"><i class="icon_clock_alt"></i> {{ blog.created_at|date:"M d" }}</a>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
      </div>
    </div>
  </section>
  <!-- ***** Blog Area End ***** -->
{% endblock %}